
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/simplebox
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
  # show_sql: true
<<<<<<< HEAD
      format_sql: true
=======
        format_sql: true
>>>>>>> 061c171083cf431d4fe7925e14a486eaa81c7c55
logging.level:
  org.hibernate.SQL: debug